// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6AIIZkXx2l7ieQe94Ebq9gtp3_wUPN0s',
    appId: '1:139443522004:web:12ad557f7911551cfd6e41',
    messagingSenderId: '139443522004',
    projectId: 'taskskillgenic',
    authDomain: 'taskskillgenic.firebaseapp.com',
    storageBucket: 'taskskillgenic.firebasestorage.app',
    measurementId: 'G-7S4LETY4BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJy9D-oRhNhBr2u8CgHyuo6Ab04rNlEQ',
    appId: '1:139443522004:android:9f44b4ada46579b8fd6e41',
    messagingSenderId: '139443522004',
    projectId: 'taskskillgenic',
    storageBucket: 'taskskillgenic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGxP91qmMo_5GKqOMDHlQ5cdH9h7LGVk',
    appId: '1:139443522004:ios:202c38b80799382bfd6e41',
    messagingSenderId: '139443522004',
    projectId: 'taskskillgenic',
    storageBucket: 'taskskillgenic.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskSkillgenic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGxP91qmMo_5GKqOMDHlQ5cdH9h7LGVk',
    appId: '1:139443522004:ios:202c38b80799382bfd6e41',
    messagingSenderId: '139443522004',
    projectId: 'taskskillgenic',
    storageBucket: 'taskskillgenic.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskSkillgenic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6AIIZkXx2l7ieQe94Ebq9gtp3_wUPN0s',
    appId: '1:139443522004:web:f93d95c7ff823cdbfd6e41',
    messagingSenderId: '139443522004',
    projectId: 'taskskillgenic',
    authDomain: 'taskskillgenic.firebaseapp.com',
    storageBucket: 'taskskillgenic.firebasestorage.app',
    measurementId: 'G-MDQB819T8L',
  );
}
